## Question 1  
Valid email ID
Description
Consider that email IDs are supposed to be for the following format:
username@website.extension.
Here, there are three conditions to keep in mind:
1. The username can only contain characters 0-9, a-z and A-Z.
2. The website name can contain only characters a-z
3. The extension can have 2 or 3 alphabets(a-z).

Given an email ID, you have to determine if it is valid or not.

Sample Input:
prerna@upgrad.com

Sample Output:
valid
Execution Time Limit
10 seconds

In [11]:
def vefication(email):
    try:
        username, other = email.split("@")
        websitename, Extension = other.split(".")
    except:
        return "Invalid"
    if username.isalnum() == False:
        return "Invalid"
    elif websitename.isalpha() == False:
        return "Invalid"
    elif len(Extension)>3:
        return "Invalid"
    else:
        return "Valid"

    
    
Email = input() 
print(vefication(Email))

prerna@upgrad.com
Valid


In [3]:
def checkmail(email):
    a=mail.split("@")
    b=a[1].split(".")
    x=[]
    flag = 0
    for i in range(len(x[0])):
        x.append(x[0][i])
    if mail.count(".")>1 or mail.count("@")>1:
        flag = 1 
    else:
        if len(b[1])==2 or len(b[1])==3 and b[1].islower():
            if b[0].islower() and b[0].isalpha():
                for i in range(len(x)):
                    if x[i].islower() or x[i].isupper() or x[i].isdigit():
                        pass
                    else:
                        flag = 1
                        else:
                flag = 1 
        else:
            flag = 1 
    if flag = 0:
        return('valid')
    else:
        return('invalid')
    
email=input()
print(checkmail(email))

SyntaxError: invalid syntax (<ipython-input-3-33b4e64b1697>, line 18)

## Question 2
Flatten a list
Description
Given a nested list, write python code to flatten the list.
Note: The input list will strictly have 2 levels, i.e. the list will be of the form [[1,2],[3,4]]. Inputs like [1,[2,3]] and [[1,[2,3],4],5] are not applicable.

For example: If the input list is :
[[1,2,3],[4,5],[6,7,8,9]]
Then the output should be:
[1,2,3,4,5,6,7,8,9]

Execution Time Limit
10 seconds

In [2]:
list = [[1,2,3],[4,5],[6,7,8,9]]
flat_list = []
for i in list:
    for j in i :
        flat_list.append(j)
print(flat_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## Question 3
Description
Given a list of positive integers, you have to find numbers divisible by 3 and replace them with their squares. 
For example, consider the list below:
Input: [1,2,3,4,5,6]
The output for the above list would be: [1,2,9,4,5,36]. Because 3 and 6 were divisible by 3, these numbers were replaced with their squares.
Execution Time Limit

In [5]:
list_sq = [1,2,3,4,5,6]
ans_list = []
for i in list_sq:
    if i%3 == 0:
        ans_list.append(i*i)
    else:
        ans_list.append(i)
print(ans_list) 

[1, 2, 9, 4, 5, 36]


## Question 4
Description
Write a program that computes the value of n+nn+nnn+nnnn with a given digit as the value of n.
For example, if n=9 , then you have to find the value of 9+99+999+9999.

In [6]:
n = int(input())
temp = str(n)
two_element = temp+temp
print(two_element)
three_element = temp+temp+temp
print(three_element)
four_element = temp+temp+temp+temp
print(four_element)
weird_sum = n+int(two_element)+int(three_element)+int(four_element)
print(weird_sum)

9
99
999
9999
11106


### Website Answer Authentic

In [7]:
n=input()
n1 = int( "%s" % n)
n2 = int( "%s%s" % (n,n) )
n3 = int( "%s%s%s" % (n,n,n) )
n4 = int( "%s%s%s%s" % (n,n,n,n) )

print (n1+n2+n3+n4)

9
11106


## Question 5
Frequent Letters
Description
Given a string, you have to find the first n most frequent characters in it.

You have to print these n letters in alphabetically sorted order.

The input will contain two lines, the first line will contain a string and the second line will contain the letter n.

The output should be a list of n most frequent letters in alphabetically sorted order.

Note: If there are two letters with the same frequency, then the alphabetically preceding alphabet should be picked first. (For example, in "aabbccc", if n=2, then output list would have c and a.)

Sample Input:

ddddaacccb

3

Sample Output: ['a', 'c', 'd']

In [8]:
string=input()
n=int(input())

import collections
out=[collections.Counter(string).most_common(i+1)[i][0] for i in range(n)]
out.sort()
print(out)

ddddaacccb
3
['a', 'c', 'd']


## Question 6
Description
Write Python code which takes 2 numbers x and y as input and generates a 2-dimensional numpy array where value in the i-th row and j-th column of the array should be (i+j)/2.
Note: i=0,1,...x-1 and j=0,1....,y-1
The input will have two lines with x and y respectively.
The output should be a 2D numpy array.
Sample Input:
3
4
Sample Output: [[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]

In [9]:
import numpy as np
x=int(input())
y=int(input())
#write your code here
def function_array(r,c):
    matrix = []
    for i in range(r):
        a = []
        for j in range(c):
            val = float((i+j)/2)
            a.append(val)
        matrix.append(a)
        arr = np.array(matrix)
    return arr

print(function_array(x,y))

#write your code here

3
4
[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]
